/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as EnrollRouteImport } from './routes/enroll'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as KriyaYogaRouteImport } from './routes/kriya-yoga'
import { Route as LineageRouteImport } from './routes/lineage'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ScienceOfKriyaYogaRouteImport } from './routes/science-of-kriya-yoga'
import { Route as SiddhaTraditionRouteImport } from './routes/siddha-tradition'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TheKriyaLabRouteImport } from './routes/the-kriya-lab'
import { Route as AuthenticatedMyProgramsRouteImport } from './routes/_authenticated/my-programs'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminProgramsRouteImport } from './routes/admin/programs'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as JournalSlugRouteImport } from './routes/journal/$slug'
import { Route as ProgramsIndexRouteImport } from './routes/programs/index'
import { Route as ProgramsIdRouteImport } from './routes/programs/$id'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as AdminEventsAddRouteImport } from './routes/admin/events/add'
import { Route as AdminEventsFutureRouteImport } from './routes/admin/events/future'
import { Route as AdminEventsPastRouteImport } from './routes/admin/events/past'
import { Route as AdminProgramsAddRouteImport } from './routes/admin/programs/add'
import { Route as AdminProgramsOfflineRouteImport } from './routes/admin/programs/offline'
import { Route as AdminProgramsOnlineRouteImport } from './routes/admin/programs/online'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollRoute = EnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const KriyaYogaRoute = KriyaYogaRouteImport.update({
  id: '/kriya-yoga',
  path: '/kriya-yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const LineageRoute = LineageRouteImport.update({
  id: '/lineage',
  path: '/lineage',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ScienceOfKriyaYogaRoute = ScienceOfKriyaYogaRouteImport.update({
  id: '/science-of-kriya-yoga',
  path: '/science-of-kriya-yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const SiddhaTraditionRoute = SiddhaTraditionRouteImport.update({
  id: '/siddha-tradition',
  path: '/siddha-tradition',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TheKriyaLabRoute = TheKriyaLabRouteImport.update({
  id: '/the-kriya-lab',
  path: '/the-kriya-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyProgramsRoute = AuthenticatedMyProgramsRouteImport.update({
  id: '/my-programs',
  path: '/my-programs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIdRoute = ProgramsIdRouteImport.update({
  id: '/programs/$id',
  path: '/programs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsAddRoute = AdminEventsAddRouteImport.update({
  id: '/events/add',
  path: '/events/add',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsFutureRoute = AdminEventsFutureRouteImport.update({
  id: '/events/future',
  path: '/events/future',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsPastRoute = AdminEventsPastRouteImport.update({
  id: '/events/past',
  path: '/events/past',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProgramsAddRoute = AdminProgramsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AdminProgramsRoute,
} as any)
const AdminProgramsOfflineRoute = AdminProgramsOfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => AdminProgramsRoute,
} as any)
const AdminProgramsOnlineRoute = AdminProgramsOnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => AdminProgramsRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/enroll': typeof EnrollRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/journey': typeof JourneyRoute
  '/kriya-yoga': typeof KriyaYogaRoute
  '/lineage': typeof LineageRoute
  '/privacy': typeof PrivacyRoute
  '/science-of-kriya-yoga': typeof ScienceOfKriyaYogaRoute
  '/siddha-tradition': typeof SiddhaTraditionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/the-kriya-lab': typeof TheKriyaLabRoute
  '/my-programs': typeof AuthenticatedMyProgramsRoute
  '/admin/programs': typeof AdminProgramsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/programs/$id': typeof ProgramsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/admin/events/add': typeof AdminEventsAddRoute
  '/admin/events/future': typeof AdminEventsFutureRoute
  '/admin/events/past': typeof AdminEventsPastRoute
  '/admin/programs/add': typeof AdminProgramsAddRoute
  '/admin/programs/offline': typeof AdminProgramsOfflineRoute
  '/admin/programs/online': typeof AdminProgramsOnlineRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/enroll': typeof EnrollRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/journey': typeof JourneyRoute
  '/kriya-yoga': typeof KriyaYogaRoute
  '/lineage': typeof LineageRoute
  '/privacy': typeof PrivacyRoute
  '/science-of-kriya-yoga': typeof ScienceOfKriyaYogaRoute
  '/siddha-tradition': typeof SiddhaTraditionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/the-kriya-lab': typeof TheKriyaLabRoute
  '/my-programs': typeof AuthenticatedMyProgramsRoute
  '/admin/programs': typeof AdminProgramsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/programs/$id': typeof ProgramsIdRoute
  '/admin': typeof AdminIndexRoute
  '/journal': typeof JournalIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/admin/events/add': typeof AdminEventsAddRoute
  '/admin/events/future': typeof AdminEventsFutureRoute
  '/admin/events/past': typeof AdminEventsPastRoute
  '/admin/programs/add': typeof AdminProgramsAddRoute
  '/admin/programs/offline': typeof AdminProgramsOfflineRoute
  '/admin/programs/online': typeof AdminProgramsOnlineRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/enroll': typeof EnrollRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/journey': typeof JourneyRoute
  '/kriya-yoga': typeof KriyaYogaRoute
  '/lineage': typeof LineageRoute
  '/privacy': typeof PrivacyRoute
  '/science-of-kriya-yoga': typeof ScienceOfKriyaYogaRoute
  '/siddha-tradition': typeof SiddhaTraditionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/the-kriya-lab': typeof TheKriyaLabRoute
  '/_authenticated/my-programs': typeof AuthenticatedMyProgramsRoute
  '/admin/programs': typeof AdminProgramsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/programs/$id': typeof ProgramsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/admin/events/add': typeof AdminEventsAddRoute
  '/admin/events/future': typeof AdminEventsFutureRoute
  '/admin/events/past': typeof AdminEventsPastRoute
  '/admin/programs/add': typeof AdminProgramsAddRoute
  '/admin/programs/offline': typeof AdminProgramsOfflineRoute
  '/admin/programs/online': typeof AdminProgramsOnlineRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/auth'
    | '/buy'
    | '/contact'
    | '/dashboard'
    | '/disclaimer'
    | '/enroll'
    | '/events'
    | '/faq'
    | '/gallery'
    | '/journey'
    | '/kriya-yoga'
    | '/lineage'
    | '/privacy'
    | '/science-of-kriya-yoga'
    | '/siddha-tradition'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/thank-you'
    | '/the-kriya-lab'
    | '/my-programs'
    | '/admin/programs'
    | '/admin/settings'
    | '/admin/users'
    | '/journal/$slug'
    | '/programs/$id'
    | '/admin/'
    | '/journal/'
    | '/programs/'
    | '/admin/events/add'
    | '/admin/events/future'
    | '/admin/events/past'
    | '/admin/programs/add'
    | '/admin/programs/offline'
    | '/admin/programs/online'
    | '/admin/events/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/buy'
    | '/contact'
    | '/dashboard'
    | '/disclaimer'
    | '/enroll'
    | '/events'
    | '/faq'
    | '/gallery'
    | '/journey'
    | '/kriya-yoga'
    | '/lineage'
    | '/privacy'
    | '/science-of-kriya-yoga'
    | '/siddha-tradition'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/thank-you'
    | '/the-kriya-lab'
    | '/my-programs'
    | '/admin/programs'
    | '/admin/settings'
    | '/admin/users'
    | '/journal/$slug'
    | '/programs/$id'
    | '/admin'
    | '/journal'
    | '/programs'
    | '/admin/events/add'
    | '/admin/events/future'
    | '/admin/events/past'
    | '/admin/programs/add'
    | '/admin/programs/offline'
    | '/admin/programs/online'
    | '/admin/events'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/about'
    | '/auth'
    | '/buy'
    | '/contact'
    | '/dashboard'
    | '/disclaimer'
    | '/enroll'
    | '/events'
    | '/faq'
    | '/gallery'
    | '/journey'
    | '/kriya-yoga'
    | '/lineage'
    | '/privacy'
    | '/science-of-kriya-yoga'
    | '/siddha-tradition'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/thank-you'
    | '/the-kriya-lab'
    | '/_authenticated/my-programs'
    | '/admin/programs'
    | '/admin/settings'
    | '/admin/users'
    | '/journal/$slug'
    | '/programs/$id'
    | '/admin/'
    | '/journal/'
    | '/programs/'
    | '/admin/events/add'
    | '/admin/events/future'
    | '/admin/events/past'
    | '/admin/programs/add'
    | '/admin/programs/offline'
    | '/admin/programs/online'
    | '/admin/events/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BuyRoute: typeof BuyRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EnrollRoute: typeof EnrollRoute
  EventsRoute: typeof EventsRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  JourneyRoute: typeof JourneyRoute
  KriyaYogaRoute: typeof KriyaYogaRoute
  LineageRoute: typeof LineageRoute
  PrivacyRoute: typeof PrivacyRoute
  ScienceOfKriyaYogaRoute: typeof ScienceOfKriyaYogaRoute
  SiddhaTraditionRoute: typeof SiddhaTraditionRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ThankYouRoute: typeof ThankYouRoute
  TheKriyaLabRoute: typeof TheKriyaLabRoute
  JournalSlugRoute: typeof JournalSlugRoute
  ProgramsIdRoute: typeof ProgramsIdRoute
  JournalIndexRoute: typeof JournalIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enroll': {
      id: '/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof EnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kriya-yoga': {
      id: '/kriya-yoga'
      path: '/kriya-yoga'
      fullPath: '/kriya-yoga'
      preLoaderRoute: typeof KriyaYogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineage': {
      id: '/lineage'
      path: '/lineage'
      fullPath: '/lineage'
      preLoaderRoute: typeof LineageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/science-of-kriya-yoga': {
      id: '/science-of-kriya-yoga'
      path: '/science-of-kriya-yoga'
      fullPath: '/science-of-kriya-yoga'
      preLoaderRoute: typeof ScienceOfKriyaYogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siddha-tradition': {
      id: '/siddha-tradition'
      path: '/siddha-tradition'
      fullPath: '/siddha-tradition'
      preLoaderRoute: typeof SiddhaTraditionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-kriya-lab': {
      id: '/the-kriya-lab'
      path: '/the-kriya-lab'
      fullPath: '/the-kriya-lab'
      preLoaderRoute: typeof TheKriyaLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-programs': {
      id: '/_authenticated/my-programs'
      path: '/my-programs'
      fullPath: '/my-programs'
      preLoaderRoute: typeof AuthenticatedMyProgramsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$id': {
      id: '/programs/$id'
      path: '/programs/$id'
      fullPath: '/programs/$id'
      preLoaderRoute: typeof ProgramsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events/add': {
      id: '/admin/events/add'
      path: '/events/add'
      fullPath: '/admin/events/add'
      preLoaderRoute: typeof AdminEventsAddRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events/future': {
      id: '/admin/events/future'
      path: '/events/future'
      fullPath: '/admin/events/future'
      preLoaderRoute: typeof AdminEventsFutureRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events/past': {
      id: '/admin/events/past'
      path: '/events/past'
      fullPath: '/admin/events/past'
      preLoaderRoute: typeof AdminEventsPastRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/programs/add': {
      id: '/admin/programs/add'
      path: '/add'
      fullPath: '/admin/programs/add'
      preLoaderRoute: typeof AdminProgramsAddRouteImport
      parentRoute: typeof AdminProgramsRoute
    }
    '/admin/programs/offline': {
      id: '/admin/programs/offline'
      path: '/offline'
      fullPath: '/admin/programs/offline'
      preLoaderRoute: typeof AdminProgramsOfflineRouteImport
      parentRoute: typeof AdminProgramsRoute
    }
    '/admin/programs/online': {
      id: '/admin/programs/online'
      path: '/online'
      fullPath: '/admin/programs/online'
      preLoaderRoute: typeof AdminProgramsOnlineRouteImport
      parentRoute: typeof AdminProgramsRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMyProgramsRoute: typeof AuthenticatedMyProgramsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMyProgramsRoute: AuthenticatedMyProgramsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminProgramsRouteChildren {
  AdminProgramsAddRoute: typeof AdminProgramsAddRoute
  AdminProgramsOfflineRoute: typeof AdminProgramsOfflineRoute
  AdminProgramsOnlineRoute: typeof AdminProgramsOnlineRoute
}

const AdminProgramsRouteChildren: AdminProgramsRouteChildren = {
  AdminProgramsAddRoute: AdminProgramsAddRoute,
  AdminProgramsOfflineRoute: AdminProgramsOfflineRoute,
  AdminProgramsOnlineRoute: AdminProgramsOnlineRoute,
}

const AdminProgramsRouteWithChildren = AdminProgramsRoute._addFileChildren(
  AdminProgramsRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminProgramsRoute: typeof AdminProgramsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEventsAddRoute: typeof AdminEventsAddRoute
  AdminEventsFutureRoute: typeof AdminEventsFutureRoute
  AdminEventsPastRoute: typeof AdminEventsPastRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminProgramsRoute: AdminProgramsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEventsAddRoute: AdminEventsAddRoute,
  AdminEventsFutureRoute: AdminEventsFutureRoute,
  AdminEventsPastRoute: AdminEventsPastRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BuyRoute: BuyRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DisclaimerRoute: DisclaimerRoute,
  EnrollRoute: EnrollRoute,
  EventsRoute: EventsRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  JourneyRoute: JourneyRoute,
  KriyaYogaRoute: KriyaYogaRoute,
  LineageRoute: LineageRoute,
  PrivacyRoute: PrivacyRoute,
  ScienceOfKriyaYogaRoute: ScienceOfKriyaYogaRoute,
  SiddhaTraditionRoute: SiddhaTraditionRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  ThankYouRoute: ThankYouRoute,
  TheKriyaLabRoute: TheKriyaLabRoute,
  JournalSlugRoute: JournalSlugRoute,
  ProgramsIdRoute: ProgramsIdRoute,
  JournalIndexRoute: JournalIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
