/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as EnrollRouteImport } from './routes/enroll'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as KriyaYogaRouteImport } from './routes/kriya-yoga'
import { Route as LineageRouteImport } from './routes/lineage'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ScienceOfKriyaYogaRouteImport } from './routes/science-of-kriya-yoga'
import { Route as SiddhaTraditionRouteImport } from './routes/siddha-tradition'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TheKriyaLabRouteImport } from './routes/the-kriya-lab'
import { Route as AuthenticatedMyProgramsRouteImport } from './routes/_authenticated/my-programs'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as JournalSlugRouteImport } from './routes/journal/$slug'
import { Route as ProgramsIndexRouteImport } from './routes/programs/index'
import { Route as ProgramsSlugRouteImport } from './routes/programs/$slug'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollRoute = EnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const KriyaYogaRoute = KriyaYogaRouteImport.update({
  id: '/kriya-yoga',
  path: '/kriya-yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const LineageRoute = LineageRouteImport.update({
  id: '/lineage',
  path: '/lineage',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ScienceOfKriyaYogaRoute = ScienceOfKriyaYogaRouteImport.update({
  id: '/science-of-kriya-yoga',
  path: '/science-of-kriya-yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const SiddhaTraditionRoute = SiddhaTraditionRouteImport.update({
  id: '/siddha-tradition',
  path: '/siddha-tradition',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TheKriyaLabRoute = TheKriyaLabRouteImport.update({
  id: '/the-kriya-lab',
  path: '/the-kriya-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyProgramsRoute = AuthenticatedMyProgramsRouteImport.update({
  id: '/my-programs',
  path: '/my-programs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/enroll': typeof EnrollRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/journey': typeof JourneyRoute
  '/kriya-yoga': typeof KriyaYogaRoute
  '/lineage': typeof LineageRoute
  '/privacy': typeof PrivacyRoute
  '/science-of-kriya-yoga': typeof ScienceOfKriyaYogaRoute
  '/siddha-tradition': typeof SiddhaTraditionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/the-kriya-lab': typeof TheKriyaLabRoute
  '/my-programs': typeof AuthenticatedMyProgramsRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/enroll': typeof EnrollRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/journey': typeof JourneyRoute
  '/kriya-yoga': typeof KriyaYogaRoute
  '/lineage': typeof LineageRoute
  '/privacy': typeof PrivacyRoute
  '/science-of-kriya-yoga': typeof ScienceOfKriyaYogaRoute
  '/siddha-tradition': typeof SiddhaTraditionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/the-kriya-lab': typeof TheKriyaLabRoute
  '/my-programs': typeof AuthenticatedMyProgramsRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/journal': typeof JournalIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/enroll': typeof EnrollRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/journey': typeof JourneyRoute
  '/kriya-yoga': typeof KriyaYogaRoute
  '/lineage': typeof LineageRoute
  '/privacy': typeof PrivacyRoute
  '/science-of-kriya-yoga': typeof ScienceOfKriyaYogaRoute
  '/siddha-tradition': typeof SiddhaTraditionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/the-kriya-lab': typeof TheKriyaLabRoute
  '/_authenticated/my-programs': typeof AuthenticatedMyProgramsRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/buy'
    | '/contact'
    | '/disclaimer'
    | '/enroll'
    | '/events'
    | '/faq'
    | '/gallery'
    | '/journey'
    | '/kriya-yoga'
    | '/lineage'
    | '/privacy'
    | '/science-of-kriya-yoga'
    | '/siddha-tradition'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/thank-you'
    | '/the-kriya-lab'
    | '/my-programs'
    | '/journal/$slug'
    | '/programs/$slug'
    | '/journal/'
    | '/programs/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/buy'
    | '/contact'
    | '/disclaimer'
    | '/enroll'
    | '/events'
    | '/faq'
    | '/gallery'
    | '/journey'
    | '/kriya-yoga'
    | '/lineage'
    | '/privacy'
    | '/science-of-kriya-yoga'
    | '/siddha-tradition'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/thank-you'
    | '/the-kriya-lab'
    | '/my-programs'
    | '/journal/$slug'
    | '/programs/$slug'
    | '/journal'
    | '/programs'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/buy'
    | '/contact'
    | '/disclaimer'
    | '/enroll'
    | '/events'
    | '/faq'
    | '/gallery'
    | '/journey'
    | '/kriya-yoga'
    | '/lineage'
    | '/privacy'
    | '/science-of-kriya-yoga'
    | '/siddha-tradition'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/thank-you'
    | '/the-kriya-lab'
    | '/_authenticated/my-programs'
    | '/journal/$slug'
    | '/programs/$slug'
    | '/journal/'
    | '/programs/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BuyRoute: typeof BuyRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EnrollRoute: typeof EnrollRoute
  EventsRoute: typeof EventsRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  JourneyRoute: typeof JourneyRoute
  KriyaYogaRoute: typeof KriyaYogaRoute
  LineageRoute: typeof LineageRoute
  PrivacyRoute: typeof PrivacyRoute
  ScienceOfKriyaYogaRoute: typeof ScienceOfKriyaYogaRoute
  SiddhaTraditionRoute: typeof SiddhaTraditionRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ThankYouRoute: typeof ThankYouRoute
  TheKriyaLabRoute: typeof TheKriyaLabRoute
  JournalSlugRoute: typeof JournalSlugRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enroll': {
      id: '/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof EnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kriya-yoga': {
      id: '/kriya-yoga'
      path: '/kriya-yoga'
      fullPath: '/kriya-yoga'
      preLoaderRoute: typeof KriyaYogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineage': {
      id: '/lineage'
      path: '/lineage'
      fullPath: '/lineage'
      preLoaderRoute: typeof LineageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/science-of-kriya-yoga': {
      id: '/science-of-kriya-yoga'
      path: '/science-of-kriya-yoga'
      fullPath: '/science-of-kriya-yoga'
      preLoaderRoute: typeof ScienceOfKriyaYogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siddha-tradition': {
      id: '/siddha-tradition'
      path: '/siddha-tradition'
      fullPath: '/siddha-tradition'
      preLoaderRoute: typeof SiddhaTraditionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-kriya-lab': {
      id: '/the-kriya-lab'
      path: '/the-kriya-lab'
      fullPath: '/the-kriya-lab'
      preLoaderRoute: typeof TheKriyaLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-programs': {
      id: '/_authenticated/my-programs'
      path: '/my-programs'
      fullPath: '/my-programs'
      preLoaderRoute: typeof AuthenticatedMyProgramsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMyProgramsRoute: typeof AuthenticatedMyProgramsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMyProgramsRoute: AuthenticatedMyProgramsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BuyRoute: BuyRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  EnrollRoute: EnrollRoute,
  EventsRoute: EventsRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  JourneyRoute: JourneyRoute,
  KriyaYogaRoute: KriyaYogaRoute,
  LineageRoute: LineageRoute,
  PrivacyRoute: PrivacyRoute,
  ScienceOfKriyaYogaRoute: ScienceOfKriyaYogaRoute,
  SiddhaTraditionRoute: SiddhaTraditionRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  ThankYouRoute: ThankYouRoute,
  TheKriyaLabRoute: TheKriyaLabRoute,
  JournalSlugRoute: JournalSlugRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
